# Global options
baseurl = "https://crl-workshop.github.io/"
canonifyurls = true
languagecode = "en"
theme = "crl-uai-2022-theme"
disableKinds = ["taxonomyTerm"]

# Params that are used in <head>
[params]
  supertitle = "NeurIPS 2023 Workshop on"
  title = "Causal Representation Learning"
  subtitle = "December 15th or 16th"
  author = "Sara Magliacane, Cian Eastwood, Yuki Asano, Claudia Shi, Atalanti Mastakouri, Sébastien Lachapelle, Caroline Uhler, Bernhard Schölkopf"
  description = "NeurIPS 2023 Workshop on Causal Representation Learning"
  keywords = ["workshop", "causal representation learning"]

# Options for Markdown renderer
[markup.goldmark.renderer]
  unsafe = true
  xHTML = true

# Main menu
[[menu.main]]
    name = "Call for Papers"
    url  = "/call-for-papers"
    weight = 1
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 2
[[menu.main]]
    name = "Dates"
    url  = "/dates"
    weight = 3
[[menu.main]]
    name = "Formatting Instructions"
    url  = "/formatting-instructions"
    weight = 4
[[menu.main]]
    name = "Organisers and Reviewers"
    url  = "/organisers-reviewers"
    weight = 5
[[menu.main]]
    name = "Accepted Papers"
    url  = "/accepted-papers"
    weight = 6
[[menu.main]]
    name = "Schedule and Format"
    url  = "/schedule-format"
    weight = 7
[[menu.main]]
    name = "Invited Speakers and Panelists"
    url  = "/invited-speakers"
    weight = 8
# [[menu.main]]
#     name = "Slides and Recording"
#     url  = "/slides-recording"
#     weight = 9